spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    # Base64 di 64+ bytes (>=512 bit per HS512). Questa Ã¨ solo per test.
    secret: ${SECURITY_SECRET_TEST}
    expiration: PT2M
    refresh-expiration: PT10M
    issuer: usermanagement-api
    audience: usermanagement-client
    header: Authorization
    prefix: Bearer
